# test

roles:
  admins:
      - user1
      - user2
  reviewers:
      - user1
      - user3
  testers:
      - user2

rules:
  rule1:
      condition:
        order: 5
        if-labeled:
          - label1
  rule2:
      condition:
        order: 2
        skip-if-labeled:
          - pending-approval
  rule3:
      condition:
        order: 1
        filter:
          extensions:
            - ".go"
  rule4:
      condition:
        filter:
          patterns:
            - ".*/docs/.*"